OBJS =	objs/ft_btree/ft_btree_apply_infix.o\
		objs/ft_btree/ft_btree_apply_prefix.o\
		objs/ft_btree/ft_btree_apply_suffix.o\
		objs/ft_btree/ft_btree_insert.o\
		objs/ft_buffer/buf_flush.o\
		objs/ft_buffer/buf_putendl.o\
		objs/ft_buffer/buf_putstr.o\
		objs/ft_buffer/buf_write.o\
		objs/ft_convert/ft_atoi.o\
		objs/ft_convert/ft_itoa.o\
		objs/ft_dlist/ft_dlst_add.o\
		objs/ft_dlist/ft_dlst_add_tail.o\
		objs/ft_dlist/ft_dlst_apply.o\
		objs/ft_dlist/ft_dlst_del.o\
		objs/ft_dlist/ft_dlst_del_init.o\
		objs/ft_dlist/ft_dlst_empty.o\
		objs/ft_dlist/ft_dlst_find.o\
		objs/ft_dlist/ft_dlst_init_head.o\
		objs/ft_dlist/ft_dlst_is_last.o\
		objs/ft_dlist/ft_dlst_is_singular.o\
		objs/ft_dlist/ft_dlst_len.o\
		objs/ft_dlist/ft_dlst_move.o\
		objs/ft_dlist/ft_dlst_move_sub.o\
		objs/ft_dlist/ft_dlst_move_sub_tail.o\
		objs/ft_dlist/ft_dlst_move_tail.o\
		objs/ft_dlist/ft_dlst_next.o\
		objs/ft_dlist/ft_dlst_prev.o\
		objs/ft_dlist/ft_dlst_replace.o\
		objs/ft_dlist/ft_dlst_replace_init.o\
		objs/ft_dlist/ft_putdlst.o\
		objs/ft_dlist/ft_putdlst_fd.o\
		objs/ft_getopt/ft_getopt.o\
		objs/ft_gnl/ft_gnl.o\
		objs/ft_hlist/ft_hlst_add.o\
		objs/ft_hlist/ft_hlst_add_tail.o\
		objs/ft_hlist/ft_hlst_apply.o\
		objs/ft_hlist/ft_hlst_del.o\
		objs/ft_hlist/ft_hlst_del_init.o\
		objs/ft_hlist/ft_hlst_empty.o\
		objs/ft_hlist/ft_hlst_init_head.o\
		objs/ft_hlist/ft_hlst_is_last.o\
		objs/ft_hlist/ft_hlst_is_singular.o\
		objs/ft_hlist/ft_hlst_len.o\
		objs/ft_hlist/ft_hlst_move.o\
		objs/ft_hlist/ft_hlst_move_tail.o\
		objs/ft_hlist/ft_hlst_prev.o\
		objs/ft_hlist/ft_hlst_replace.o\
		objs/ft_hlist/ft_hlst_replace_init.o\
		objs/ft_hmap/ft_hmap_delete.o\
		objs/ft_hmap/ft_hmap_get.o\
		objs/ft_hmap/ft_hmap_init.o\
		objs/ft_hmap/ft_hmap_new.o\
		objs/ft_hmap/ft_hmap_set.o\
		objs/ft_hmap/ft_hmap_unset.o\
		objs/ft_hmap/ft_puthmap.o\
		objs/ft_mem/ft_bzero.o\
		objs/ft_mem/ft_memalloc.o\
		objs/ft_mem/ft_memccpy.o\
		objs/ft_mem/ft_memchr.o\
		objs/ft_mem/ft_memcmp.o\
		objs/ft_mem/ft_memcpy.o\
		objs/ft_mem/ft_memdel.o\
		objs/ft_mem/ft_memmove.o\
		objs/ft_mem/ft_memset.o\
		objs/ft_message/ft_msgget_id.o\
		objs/ft_message/ft_msgget_msg.o\
		objs/ft_misc/ft_iabs.o\
		objs/ft_misc/ft_ilen.o\
		objs/ft_misc/ft_imax.o\
		objs/ft_misc/ft_imin.o\
		objs/ft_misc/ft_isalnum.o\
		objs/ft_misc/ft_isalpha.o\
		objs/ft_misc/ft_isascii.o\
		objs/ft_misc/ft_isdigit.o\
		objs/ft_misc/ft_isdigit_only.o\
		objs/ft_misc/ft_isprint.o\
		objs/ft_misc/ft_isspace.o\
		objs/ft_misc/ft_tolower.o\
		objs/ft_misc/ft_toupper.o\
		objs/ft_mlx/ft_draw_getc.o\
		objs/ft_mlx/ft_draw_img.o\
		objs/ft_mlx/ft_draw_pix.o\
		objs/ft_mlx/ft_draw_square.o\
		objs/ft_path/ft_path_clean.o\
		objs/ft_path/ft_path_get_file.o\
		objs/ft_path/ft_path_get_folder.o\
		objs/ft_path/ft_path_getcwd.o\
		objs/ft_path/ft_path_isrelative.o\
		objs/ft_path/ft_path_istype.o\
		objs/ft_path/ft_path_resolve.o\
		objs/ft_put/ft_putbin.o\
		objs/ft_put/ft_putbin_fd.o\
		objs/ft_put/ft_putchar.o\
		objs/ft_put/ft_putchar_fd.o\
		objs/ft_put/ft_putendl.o\
		objs/ft_put/ft_putendl_fd.o\
		objs/ft_put/ft_puthex.o\
		objs/ft_put/ft_puthex_fd.o\
		objs/ft_put/ft_putlli_base_fd.o\
		objs/ft_put/ft_putnbr.o\
		objs/ft_put/ft_putnbr_fd.o\
		objs/ft_put/ft_putnl.o\
		objs/ft_put/ft_putnl_fd.o\
		objs/ft_put/ft_putstr.o\
		objs/ft_put/ft_putstr_fd.o\
		objs/ft_put/ft_putulli_base_fd.o\
		objs/ft_put/ft_putunbr.o\
		objs/ft_put/ft_putunbr_fd.o\
		objs/ft_putf/ft_putf.o\
		objs/ft_putf/putf_c.o\
		objs/ft_putf/putf_format.o\
		objs/ft_putf/putf_i.o\
		objs/ft_putf/putf_putarg_fd.o\
		objs/ft_putf/putf_s.o\
		objs/ft_putf/putf_u.o\
		objs/ft_str/ft_strcat.o\
		objs/ft_str/ft_strchr.o\
		objs/ft_str/ft_strclr.o\
		objs/ft_str/ft_strcmp.o\
		objs/ft_str/ft_strcpy.o\
		objs/ft_str/ft_strdel.o\
		objs/ft_str/ft_strdup.o\
		objs/ft_str/ft_strequ.o\
		objs/ft_str/ft_strequ_nc.o\
		objs/ft_str/ft_striter.o\
		objs/ft_str/ft_striteri.o\
		objs/ft_str/ft_strjoin.o\
		objs/ft_str/ft_strlcat.o\
		objs/ft_str/ft_strlen.o\
		objs/ft_str/ft_strlen_c.o\
		objs/ft_str/ft_strlen_func.o\
		objs/ft_str/ft_strmap.o\
		objs/ft_str/ft_strmapi.o\
		objs/ft_str/ft_strncat.o\
		objs/ft_str/ft_strncmp.o\
		objs/ft_str/ft_strncpy.o\
		objs/ft_str/ft_strnequ.o\
		objs/ft_str/ft_strnew.o\
		objs/ft_str/ft_strnlen.o\
		objs/ft_str/ft_strnstr.o\
		objs/ft_str/ft_strrchr.o\
		objs/ft_str/ft_strsplit.o\
		objs/ft_str/ft_strsplit_space.o\
		objs/ft_str/ft_strstr.o\
		objs/ft_str/ft_strsub.o\
		objs/ft_str/ft_strtrim.o\
		objs/ft_string/ft_string_add.o\
		objs/ft_string/ft_string_cat.o\
		objs/ft_string/ft_string_clear.o\
		objs/ft_string/ft_string_convert.o\
		objs/ft_string/ft_string_cpy.o\
		objs/ft_string/ft_string_del.o\
		objs/ft_string/ft_string_insert.o\
		objs/ft_string/ft_string_ncat.o\
		objs/ft_string/ft_string_ncpy.o\
		objs/ft_string/ft_string_new.o\
		objs/ft_string/ft_string_remove.o\
		objs/ft_string/ft_string_resize.o\
		objs/ft_string/ft_string_sub.o\
		objs/ft_tab/ft_puttab.o\
		objs/ft_tab/ft_puttab_fd.o\
		objs/ft_tab/ft_tabcat.o\
		objs/ft_tab/ft_tabcpy.o\
		objs/ft_tab/ft_tabdel.o\
		objs/ft_tab/ft_tabdup.o\
		objs/ft_tab/ft_tablen.o\
		objs/ft_tab/ft_tabnew.o\
		objs/ft_tab/ft_tabsort_quick.o\
