# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ggilaber <ggilaber@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/11/12 15:14:11 by ggilaber          #+#    #+#              #
#    Updated: 2015/11/12 20:32:08 by ggilaber         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=test
SRC=main.cpp
FLAG=-Wall -Wextra -Werror

all: $(NAME)

$(NAME): $(SRC)
	clang++ $(FLAG) -o $(NAME) $(SRC)
